cluster:
  cloud: amazon
  location: us-west-2
  name: baluchickenag9f
  postHooks:
    InstallLogging:
      bucketName: baluchicken-test-spark-b1
      region: eu-west-1
      secretId: 1edc3c56ed97cfbbfc68ed64cd9fc7d1e16a73512217b912346aef93dc6e468a
    InstallMonitoring:
      enabled: true
  properties:
    eks:
      nodePools:
        pool1:
          autoscaling: true
          count: 2
          instanceType: t2.medium
          maxCount: 3
          minCount: 2
          spotPrice: "0"
        pool2:
          autoscaling: true
          count: 2
          instanceType: t2.medium
          maxCount: 3
          minCount: 2
          spotPrice: "0.05"
        system:
          autoscaling: true
          count: 1
          instanceType: t2.medium
          maxCount: 2
          minCount: 1
      version: "1.10"
  secretId: 1edc3c56ed97cfbbfc68ed64cd9fc7d1e16a73512217b912346aef93dc6e468a
pipeline:
  install_history_server_bucket_secrets:
    action: InstallSecret
    clusterSecret:
      convertToPreferredFormat: true
      merge: true
      name: aws-balu
      namespace: default
      spec: []
    image: banzaicloud/ci-pipeline-client:0.8
  install_history_server_auth_secrets:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: historyserverpass
      namespace: default
      spec: []
    image: banzaicloud/ci-pipeline-client:0.8
  package_application:
    image: lachlanevenson/k8s-helm:latest
    commands:
    - helm init -c
    - helm package ./.banzaicloud/charts/spotguide-spark
  deploy_application:
    action: EnsureDeployment
    deployment:
      name: ./spotguide-spark-1.0.0.tgz
      releaseName: '{{ .CICD_REPO_NAME }}'
      values:
        banzaicloud:
          bucket:
            storageAccountName: null
          secret:
            historyServer:
              name: historyserverpass
          spark:
            executor:
              num: "2"
            image:
              name: banzaicloud/spark:v2.4.0.147
            version: 2.4.0
        historyServer:
          enabled: true
        spark:
          monitoring:
            enabled: true
            jmxCollector: |
              lowercaseOutputName: false
              lowercaseOutputLabelNames: false
              whitelistObjectNames: ["*:*"]
            metricsProperties: |
              # Enable Prometheus for all instances by class name
              *.sink.prometheus.class=com.banzaicloud.spark.metrics.sink.PrometheusSink
              # Prometheus pushgateway address
              *.sink.prometheus.pushgateway-address=prometheus-pushgateway.pipeline-system:9091
              *.sink.prometheus.pushgateway-enable-timestamp=true
              *.sink.prometheus.enable-dropwizard-collector=true
              *.sink.prometheus.enable-jmx-collector=false
          spark-hs:
            ingress:
              annotations:
                ingress.kubernetes.io/ssl-redirect: "true"
                kubernetes.io/ingress.class: traefik
                traefik.frontend.rule.type: PathPrefixStrip
                traefik.ingress.kubernetes.io/auth-secret: historyserverpass
                traefik.ingress.kubernetes.io/auth-type: basic
              enabled: true
              hosts:
              - shs-{{.CICD_REPO_NAME}}-{{.CLUSTER_NAME}}.{{.ORG_NAME}}.{{.DOMAIN_NAME}}
            sparkEventLogStorage:
              azureStorageAccountName: null
              cloudProvider: amazon
              logDirectory: sparkeventlogs-mozt
              secretName: aws-balu
    image: banzaicloud/ci-pipeline-client:0.8
